name: Deploy NextJS Course Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install, export
        run: |
          npm install
          npm run export
      - name: Deploy site to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
          # fqdn: sql.holt.courses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            uses: xorilog/twitter-action@master
      - name: Tweet
      - message: "Hi, this is a test tweet!"
      env:
        TWITTER_CONSUMER_KEY: "${{ secrets.TWITTER_CONSUMER_API_KEY }}"
        TWITTER_CONSUMER_SECRET: "${{ secrets.TWITTER_CONSUMER_API_SECRET }}"
        TWITTER_ACCESS_TOKEN: "${{ secrets.TWITTER_ACCESS_TOKEN }}"
        TWITTER_ACCESS_SECRET: "${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}"
