name: Tweet about release

on: deployment

jobs:
  tweet:
    runs-on: ubuntu-latest
  env:
    CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
    CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
    ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
    ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  steps:
    - name: Tweet details
      uses: snow-actions/tweet@v1.3.0
      with:
        status: |
          Additional information
        in_reply_to_status_id: ${{ fromJSON(steps.summary.outputs.response).id_str }}
